<h1>Edit User</h1><br>
<form action="/users/<?= htmlspecialchars($user['id']); ?>" method="post">
    <input type="hidden" name="_METHOD" value="PATCH">
    <div>
       <label>
            ID
            <input type="text" name="user[id]" value="<?= htmlspecialchars($user['id']) ?>" disabled>
        </label>
    </div>
    <div>
       <label>
            Имя пользователя
            <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
        </label>
        <?php if (!empty($errors['nickname'])) :?>
            <div><?= $errors['nickname'] ?></div>
        <?php endif; ?>
    </div>
    <div>
        <label>
            Email
            <input type="email" name="user[email]" value="<?= htmlspecialchars($user['email']) ?? '' ?>">
        </label>
        <?php if (!empty($errors['email'])) :?>
            <div><?= $errors['email'] ?></div>
        <?php endif; ?>
    </div>
    <input type="submit" value="Submit">
</form>