<?php if (!empty($flash)) :?>
    <div><?= $flash['success'][0] ?></div>
<?php endif; ?>
<?php if (!empty($_SESSION['user'])) :?>
    <h3>Hello, <?= $_SESSION['user']['nickname'] ?></h3>
    <form action="/logout" method="get">
        <input type="submit" value="Logout">
    </form>
<?php endif; ?>
<h1>Users list</h1>
<a href="/users/new">Create new user</a><br><br>
<form action="/users" method="get">
    <input type="search" name="term">
    <input type="submit" value="Search">
</form>
<ol>
    <?php foreach ($users as $user) :?>
    <li>
        <ul>
            <li>Nickname: <?= htmlspecialchars($user['nickname']); ?></li>
            <li>Email: <?= htmlspecialchars($user['email']); ?></li>
            <li><a href="users/<?= htmlspecialchars($user['id']); ?>/edit">Редактировать</a></li>
            <li>
                <form action="users/<?= htmlspecialchars($user['id']); ?>" method="post">
                    <input type="hidden" name="_METHOD" value="DELETE">
                    <input type="submit" value="Delete">
                </form>
            </li>
        </ul>
    </li>
    <?php endforeach; ?>
</ol>